In [2]:
import numpy as np
arr_a=np.array([1,2,3,2,3,4,3,4,5,6])
arr_b=np.array([7,2,10,2,7,4,9,4,9,8])
print(arr_a)
print(arr_b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]


In [6]:
arr_c=np.intersect1d(arr_a,arr_b)
print(arr_c)

[2 4]


In [3]:
arr_e=np.array([2,6,1,9,10,3,27,8,6,25,16])
arr_f=[]
for i in arr_e:
    if i>=5 and i<=10:
        arr_f=np.append(arr_f,i)
print(arr_f)    

[ 6.  9. 10.  8.  6.]
