In [ ]:
#1
import numpy as np
arr_zeros=np.zeros(10)
print(arr_zeros)

arr_zeros[5]=1
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [ ]:
#2
arr_h=np.arange(10,25,1)
print(arr_h)

arr_h_nguoc=np.flip(arr_h)
print(arr_h_nguoc)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [28]:
#3
arr_1=[]
arr_k=np.array([1,2,0,8,2,0,1,3,0,5,0])
for i in arr_k:
    if i!=0:
        arr_1=np.append(arr_k,i)
print(arr_1)

[1 2 0 8 2 0 1 3 0 5 0 5]


In [29]:
#4
arr_1=np.append(arr_1,[10,24])
print(arr_1)

[ 1  2  0  8  2  0  1  3  0  5  0  5 10 24]


In [30]:
#5
arr_1[5]=100
print(arr_1)

[  1   2   0   8   2 100   1   3   0   5   0   5  10  24]


In [32]:
#6
arr_1=np.delete(arr_1,[0,1,2])
print(arr_1)

[  8   2 100   1   3   0   5   0   5  10  24]
