In [ ]:
#1
import numpy as np
arr=np.full((3,3),True)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [51]:
#2
arr_1D=np.array([0,1,2,3,4,5,6,7,8])
arr_2D=arr_1D.reshape(3,3)
print(arr_2D)

arr_2D[:,[0,2]]=arr_2D[:,[2,0]]
print("sau khi doi cot 1 va cot 3\n",arr_2D)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
sau khi doi cot 1 va cot 3
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


In [52]:
#3
arr_2D[[0,1]]=arr_2D[[1,0]]
print("sau khi doi dong 1 va dong 2\n",arr_2D)

sau khi doi dong 1 va dong 2
 [[5 4 3]
 [2 1 0]
 [8 7 6]]


In [57]:
#4
arr_2D_nguoc_dong=np.flip(arr_2D,axis=0)
print("dao nguoc cac dong\n",arr_2D_nguoc_dong)

dao nguoc cac dong
 [[8 7 6]
 [2 1 0]
 [5 4 3]]


In [56]:
#5
arr_2D_nguoc_cot=np.flip(arr_2D_nguoc_dong,axis=1)
print("dao nguoc cac cot\n",arr_2D_nguoc_cot)

dao nguoc cac cot
 [[6 7 8]
 [0 1 2]
 [3 4 5]]


In [ ]:
#6
arr_2D_null=np.array([[1,2,3],
                      [np.nan,5,6],
                      [7,np.nan,9],
                      [4,5,6]])
print(arr_2D_null)
print(np.isnan(arr_2D_null).any())

True
[[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]
 [ 4.  5.  6.]]


In [74]:
#7
print(np.nan_to_num(arr_2D_null,0))

[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
