In [1]:
import numpy as np
arr = np.array([[1, 2, 3], ])

In [2]:
import numpy as np

arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

arr_view = arr_2d[:2, :2].view()

In [13]:
arr = np.arange(1,10)            
print(f'mang 1 chieu ban dau: \n',arr)
grid= arr.reshape((3,3))

print(f'mang 2 chieu sau khi reshape: \n',grid)

mang 1 chieu ban dau: 
 [1 2 3 4 5 6 7 8 9]
mang 2 chieu sau khi reshape: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
!pip install numpy


   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.8 MB 3.4 MB/s eta 0:00:04
   ------ --------------------------------- 2.1/12.8 MB 3.8 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.8 MB 4.4 MB/s eta 0:00:03
   -------------- ------------------------- 4.7/12.8 MB 4.8 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.8 MB 5.4 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.8 MB 6.1 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.8 MB 6.7 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.8 MB 6.3 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 6.5 MB/s  0:00:02



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
import numpy as np
import time

arr = np.arange(100000000, dtype=np.int64)


In [10]:
import numpy as np 
import time 

arr = np.arange(100000000, dtype=np.int64) 

start_time = time.time() 
total = np.int64(0) 
for num in arr: 
    total += num 
end_time = time.time() 
elapsed_time_loop = end_time - start_time 
print("Tổng các phần tử mảng arr khi sử dụng vòng lặp:", total) 
print("Thời gian (giây) khi sử dụng vòng lặp:", elapsed_time_loop) 
 
start_time = time.time() 
total = np.sum(arr) 
end_time = time.time() 
elapsed_time_npsum = end_time - start_time 
print("Tổng các phần tử mảng arr khi sử dụng hàm np.sum():", total) 
print("Thời gian (giây) khi sử dụng np.sum():", elapsed_time_npsum) 
num_times_faster = elapsed_time_loop / elapsed_time_npsum 
print("Sử dụng vòng lặp chậm hơn: ~",int(num_times_faster),"lần")

Tổng các phần tử mảng arr khi sử dụng vòng lặp: 4999999950000000
Thời gian (giây) khi sử dụng vòng lặp: 20.793425798416138
Tổng các phần tử mảng arr khi sử dụng hàm np.sum(): 4999999950000000
Thời gian (giây) khi sử dụng np.sum(): 0.056630611419677734
Sử dụng vòng lặp chậm hơn: ~ 367 lần


In [ ]:
import sys

!{sys.executable} -m pip install --upgrade numpy

In [14]:
import numpy as np 
import timeit

np_setup = "import numpy as np; np_array = np.arange(1, 1000001)" 
np_code  = "np_sum = np.sum(np_array)" 
np_time  = timeit.timeit(stmt=np_code, setup=np_setup, number=10) 

list_setup = "list_array = list(range(1, 1000001))" 
list_code = "list_sum = sum(list_array)" 
list_time = timeit.timeit(stmt=list_code, setup=list_setup, 
number=10) 
 
print("Thời gian tính toán của Numpy:", np_time) 
print("Thời gian tính toán của List:", list_time) 
 
print("Numpy tính nhanh hơn List ở lượt chạy là ~ ", int(list_time/np_time), "lần!!")

Thời gian tính toán của Numpy: 0.012378400002489798
Thời gian tính toán của List: 0.0803788999983226
Numpy tính nhanh hơn List ở lượt chạy là ~  6 lần!!


In [1]:
import numpy as np 
 
arr1 = np.array([1, 2, 3]) 
arr2 = np.array([4, 5, 6]) 

Tong = np.add(arr1,arr2) 
 
Hieu = np.subtract(arr1,arr2) 
 
Tich = np.multiply(arr1,arr2)

Thuong = np.divide(arr1,arr2)
 
print("Tổng của arr1 + arr2 là:",Tong) 
print("Hiệu của arr1 - arr2 là:",Hieu) 
print("Tích của arr1 * arr2 là:",Tich) 
print("Thương của arr1/arr2 là:",Thuong)

Tổng của arr1 + arr2 là: [5 7 9]
Hiệu của arr1 - arr2 là: [-3 -3 -3]
Tích của arr1 * arr2 là: [ 4 10 18]
Thương của arr1/arr2 là: [0.25 0.4  0.5 ]
